export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#0a0a0a \
  --color=bg:#000000 \
  --color=border:#1f1f1f \
  --color=fg:#3d3d3d \
  --color=gutter:#101724 \
  --color=header:#a3a3a3 \
  --color=hl+:#0df29e \
  --color=hl:#0bcb85 \
  --color=info:#adadad \
  --color=marker:#FF5C00 \
  --color=pointer:#FF5C00 \
  --color=prompt:#474747 \
  --color=query:#c2c2c2:regular \
  --color=scrollbar:#0bcb85 \
  --color=separator:#a3a3a3 \
  --color=spinner:#FF5C00 \
"
